[project]
name = "fast-phonemizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.11.0",
    "datasets>=4.4.1",
    "pyyaml>=6.0.3",
    "tokenizers>=0.22.1",
    "torch>=2.9.0",
    "transformers>=4.44",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "pyright>=1.1.407",
]
